version: '3'
services:
   grafana:
      image: grafana/grafana
      container_name: grafana
      restart: always
      ports:
         - '17300:3000'
      volumes:
         - ./grafana/var/lib:/var/lib/grafana
      environment:
         - GF_INSTALL_PLUGINS=yesoreyeram-boomtheme-panel,savantly-heatmap-panel,ryantxu-ajax-panel
         - GF_SECURITY_ALLOW_EMBEDDING=true
         - GF_AUTH_ANONYMOUS_ENABLED=true
         - GF_SECURITY_COOKIE_SAMESITE=none
         - GF_SECURITY_COOKIE_SECURE=true
      networks:
         dc2net:
            ipv4_address: 172.28.1.3
   influxdb:
      image: influxdb
      container_name: influxdb
      restart: always
      volumes:
         - ./influxdb:/var/lib/influxdb
      environment:
         - INFLUXDB_ADMIN_USER=admin
         - INFLUXDB_USER=user
         - INFLUXDB_ADMIN_PASSWORD=COV1D9@ubbclujFX
         - INFLUXDB_USER_PASSWORD=COV1D9@ubbclujFU
      networks:
         dc2net:
            ipv4_address: 172.28.1.2
   jupyter:
      build: ./jupyter
      container_name: jupyter
      restart: always
      ports:
         - '17888:8888'
      volumes:
         - ./jupyter:/home/jovyan/work
         - ./html:/html
      networks:
         dc2net:
            ipv4_address: 172.28.1.1
   nginx:
      image: nginx
      container_name: nginx
      restart: always
      ports:
         - '80:80'
         - '443:443'
      volumes:
         - ./html:/usr/share/nginx/html
      networks:
         dc2net:
            ipv4_address: 172.28.1.4
networks:
    dc2net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
